// ── Demo action catalogue ─────────────────────────────────────────────────────
// One complete, richly-populated action per type.
// These are injected into the live store when demo mode is enabled.
// Each action has a demoOnly: true marker so they can be flushed on disable.

export const DEMO_ACTIONS = [
  // ── 1. Investigation ───────────────────────────────────────────────────────
  {
    id: 'demo-1',
    actionNumber: 'INV-004',
    demoOnly: true,
    title: 'Critical Asset Failure Investigation',
    description: 'Identified 15 rotating assets with recurring failures and prioritized them by criticality, failure frequency, and downtime impact.',
    type: 'Investigation',
    status: 'Completed',
    priority: 'High',
    assets: 15,
    created: 'Today, 10:24 AM',
    source: 'Chat',
    sourceConversationId: 'demo-conv-001',
    parentActionId: null,
    relatedActions: ['demo-2', 'demo-3', 'demo-7'],
    metrics: {
      totalAssets: 15,
      totalFailures: 78,
      totalDowntime: '1,240 hrs',
      highPriorityAssets: 5,
    },
    priorityAssets: [
      { asset: 'PUMP-2547', description: 'Booster Pump 2547',  criticality: 'Critical', failures: 12, downtime: '256 hrs', priority: 'High',   reason: 'High failure rate & unplanned downtime' },
      { asset: 'COMP-1103', description: 'Compressor 1103',    criticality: 'Critical', failures: 8,  downtime: '198 hrs', priority: 'High',   reason: 'Recurring seal failures' },
      { asset: 'PUMP-0392', description: 'Process Pump 0392',  criticality: 'High',     failures: 7,  downtime: '142 hrs', priority: 'Medium', reason: 'High maintenance recurrence' },
      { asset: 'TANK-0051', description: 'Storage Tank 0051',  criticality: 'High',     failures: 5,  downtime: '110 hrs', priority: 'Medium', reason: 'Repeated alarms and leaks' },
      { asset: 'MOT-8821',  description: 'Motor 8821',         criticality: 'Medium',   failures: 4,  downtime: '68 hrs',  priority: 'Low',    reason: 'Bearing overheating trend' },
    ],
    allAssets: [
      { asset: 'PUMP-2547', description: 'Booster Pump 2547',   location: 'Unit 3', criticality: 'Critical', failures: 12, downtime: '256 hrs', lastFailure: 'Apr 28, 2025', currentPM: 'PM-PUMP-2547', priority: 'High' },
      { asset: 'COMP-1103', description: 'Compressor 1103',     location: 'Unit 1', criticality: 'Critical', failures: 8,  downtime: '198 hrs', lastFailure: 'May 2, 2025',  currentPM: 'PM-COMP-1103', priority: 'High' },
      { asset: 'PUMP-0392', description: 'Process Pump 0392',   location: 'Unit 2', criticality: 'High',     failures: 7,  downtime: '142 hrs', lastFailure: 'May 5, 2025',  currentPM: 'PM-PUMP-0392', priority: 'Medium' },
      { asset: 'TANK-0051', description: 'Storage Tank 0051',   location: 'Unit 4', criticality: 'High',     failures: 5,  downtime: '110 hrs', lastFailure: 'Apr 30, 2025', currentPM: 'PM-TANK-0051', priority: 'Medium' },
      { asset: 'MOT-8821',  description: 'Motor 8821',          location: 'Unit 1', criticality: 'Medium',   failures: 4,  downtime: '68 hrs',  lastFailure: 'Apr 25, 2025', currentPM: 'PM-MOT-8821',  priority: 'Low' },
      { asset: 'PUMP-1144', description: 'Booster Pump 1144',   location: 'Unit 2', criticality: 'High',     failures: 3,  downtime: '54 hrs',  lastFailure: 'Apr 18, 2025', currentPM: 'PM-PUMP-1144', priority: 'Medium' },
      { asset: 'COMP-0881', description: 'Compressor 0881',     location: 'Unit 3', criticality: 'High',     failures: 3,  downtime: '48 hrs',  lastFailure: 'Apr 14, 2025', currentPM: 'PM-COMP-0881', priority: 'Medium' },
      { asset: 'PUMP-0775', description: 'Process Pump 0775',   location: 'Unit 4', criticality: 'Medium',   failures: 3,  downtime: '42 hrs',  lastFailure: 'Apr 10, 2025', currentPM: 'PM-PUMP-0775', priority: 'Low' },
      { asset: 'TANK-0113', description: 'Storage Tank 0113',   location: 'Unit 1', criticality: 'Medium',   failures: 2,  downtime: '36 hrs',  lastFailure: 'Mar 29, 2025', currentPM: 'PM-TANK-0113', priority: 'Low' },
      { asset: 'MOT-4402',  description: 'Motor 4402',          location: 'Unit 2', criticality: 'Medium',   failures: 2,  downtime: '28 hrs',  lastFailure: 'Mar 25, 2025', currentPM: 'PM-MOT-4402',  priority: 'Low' },
      { asset: 'PUMP-2201', description: 'Injection Pump 2201', location: 'Unit 3', criticality: 'High',     failures: 2,  downtime: '24 hrs',  lastFailure: 'Mar 20, 2025', currentPM: 'PM-PUMP-2201', priority: 'Low' },
      { asset: 'COMP-0334', description: 'Compressor 0334',     location: 'Unit 4', criticality: 'Medium',   failures: 2,  downtime: '20 hrs',  lastFailure: 'Mar 15, 2025', currentPM: 'PM-COMP-0334', priority: 'Low' },
      { asset: 'PUMP-0610', description: 'Transfer Pump 0610',  location: 'Unit 1', criticality: 'Low',      failures: 1,  downtime: '12 hrs',  lastFailure: 'Mar 8, 2025',  currentPM: 'PM-PUMP-0610', priority: 'Low' },
      { asset: 'TANK-0228', description: 'Buffer Tank 0228',    location: 'Unit 2', criticality: 'Low',      failures: 1,  downtime: '8 hrs',   lastFailure: 'Feb 28, 2025', currentPM: 'PM-TANK-0228', priority: 'Low' },
      { asset: 'MOT-0991',  description: 'Drive Motor 0991',    location: 'Unit 3', criticality: 'Low',      failures: 1,  downtime: '6 hrs',   lastFailure: 'Feb 20, 2025', currentPM: 'PM-MOT-0991',  priority: 'Low' },
    ],
    failurePatterns: [
      { mode: 'Seal leakage',        occurrences: 12, affectedAssets: 4, severity: 'High',   lastOccurrence: 'May 2, 2025',  trend: 'Increasing' },
      { mode: 'Bearing overheating', occurrences: 8,  affectedAssets: 3, severity: 'High',   lastOccurrence: 'Apr 28, 2025', trend: 'Stable' },
      { mode: 'High vibration',      occurrences: 7,  affectedAssets: 3, severity: 'Medium', lastOccurrence: 'May 5, 2025',  trend: 'Increasing' },
      { mode: 'Lubrication issue',   occurrences: 5,  affectedAssets: 4, severity: 'Medium', lastOccurrence: 'Apr 30, 2025', trend: 'Stable' },
      { mode: 'Valve failure',       occurrences: 3,  affectedAssets: 2, severity: 'Low',    lastOccurrence: 'Apr 15, 2025', trend: 'Decreasing' },
    ],
    workOrders: [
      { wo: 'WO-10421', asset: 'PUMP-2547', description: 'Seal replacement',           type: 'Corrective', status: 'Closed',       reported: 'Apr 20, 2025', completed: 'Apr 22, 2025', downtime: '48 hrs' },
      { wo: 'WO-10398', asset: 'COMP-1103', description: 'Bearing inspection',         type: 'Corrective', status: 'Closed',       reported: 'Apr 10, 2025', completed: 'Apr 12, 2025', downtime: '36 hrs' },
      { wo: 'WO-10502', asset: 'PUMP-0392', description: 'Vibration check',            type: 'Corrective', status: 'In Progress',  reported: 'May 5, 2025',  completed: '—',            downtime: '18 hrs' },
      { wo: 'WO-10315', asset: 'TANK-0051', description: 'Leak investigation',         type: 'Corrective', status: 'Closed',       reported: 'Mar 28, 2025', completed: 'Apr 1, 2025',  downtime: '72 hrs' },
      { wo: 'WO-10488', asset: 'MOT-8821',  description: 'Bearing temperature check',  type: 'Preventive', status: 'Scheduled',    reported: 'May 3, 2025',  completed: '—',            downtime: '0 hrs' },
    ],
    recommendations: [
      { recommendation: 'Align lubrication interval with OEM recommendation for PUMP-2547', assets: 2, priority: 'High',   expectedBenefit: 'Reduce failures by 30%',             evidence: 'OEM Manual Section 5.4', status: 'Proposed' },
      { recommendation: 'Increase bearing inspection frequency for COMP-1103',              assets: 2, priority: 'High',   expectedBenefit: 'Earlier detection of bearing wear',  evidence: 'Failure pattern analysis',    status: 'Proposed' },
      { recommendation: 'Add seal condition check to PM tasks',                              assets: 1, priority: 'High',   expectedBenefit: 'Early detection of seal wear',        evidence: 'WO-10421 history',            status: 'Proposed' },
      { recommendation: 'Standardize PM tasks with OEM best practices',                     assets: 3, priority: 'Medium', expectedBenefit: 'Consistency across assets',           evidence: 'OEM Maintenance Manual',      status: 'Proposed' },
    ],
  },

  // ── 2. Analysis ────────────────────────────────────────────────────────────
  {
    id: 'demo-2',
    actionNumber: 'ANA-004',
    demoOnly: true,
    title: 'Job Plan vs OEM Gap Analysis — Rotating Equipment',
    description: 'Compared current Maximo job plans against OEM maintenance recommendations. Identified 7 assets with maintenance gaps requiring review.',
    type: 'Analysis',
    status: 'In Review',
    priority: 'High',
    assets: 7,
    created: 'Today, 11:05 AM',
    source: 'Chat',
    sourceConversationId: 'demo-conv-001',
    parentActionId: 'demo-1',
    relatedActions: ['demo-1', 'demo-3', 'demo-7'],
    metrics: { assetsEvaluated: 15, requireReview: 7, gapsIdentified: 10, aligned: 8 },
    gapSummaryByCategory: [
      { category: 'Maintenance Interval',  count: 4, pct: '40%' },
      { category: 'Inspection Frequency',  count: 3, pct: '30%' },
      { category: 'Maintenance Tasks',     count: 2, pct: '20%' },
      { category: 'Lubrication',           count: 1, pct: '10%' },
    ],
    gapSeverity: [
      { severity: 'High',    count: 4 },
      { severity: 'Medium',  count: 3 },
      { severity: 'Low',     count: 0 },
      { severity: 'Aligned', count: 8 },
    ],
    assetsWithGaps: [
      { asset: 'PUMP-2547', description: 'Booster Pump 2547',  criticality: 'Critical', gapCount: 2, highestGap: 'Maintenance Interval', status: 'Gap Identified',  priority: 'High' },
      { asset: 'COMP-1103', description: 'Compressor 1103',    criticality: 'Critical', gapCount: 2, highestGap: 'Inspection Frequency', status: 'Review Required', priority: 'High' },
      { asset: 'PUMP-0392', description: 'Process Pump 0392',  criticality: 'High',     gapCount: 1, highestGap: 'Maintenance Tasks',    status: 'Review Required', priority: 'Medium' },
      { asset: 'TANK-0051', description: 'Storage Tank 0051',  criticality: 'High',     gapCount: 1, highestGap: 'Inspection Frequency', status: 'Review Required', priority: 'Medium' },
    ],
    currentJobPlans: [
      { asset: 'PUMP-2547', jobPlan: 'JP-PUMP-2547', task: 'Lubrication check',     frequency: 'Every 6 months', procedure: 'Apply grease per spec',      lastUpdated: 'Jan 2024' },
      { asset: 'PUMP-2547', jobPlan: 'JP-PUMP-2547', task: 'Seal inspection',       frequency: 'Annual',         procedure: 'Visual inspection only',      lastUpdated: 'Jan 2024' },
      { asset: 'COMP-1103', jobPlan: 'JP-COMP-1103', task: 'Bearing inspection',    frequency: 'Quarterly',      procedure: 'Visual + temperature check',  lastUpdated: 'Mar 2024' },
      { asset: 'COMP-1103', jobPlan: 'JP-COMP-1103', task: 'Vibration measurement', frequency: 'Semi-annual',    procedure: 'Manual vibration logging',    lastUpdated: 'Mar 2024' },
    ],
    oemRecommendations: [
      { asset: 'PUMP-2547', document: 'Pump Series X OEM Manual', section: '5.4 Lubrication', recommendation: 'Lubricate every 3 months',     frequency: 'Every 3 months', docDate: '2024', evidence: 'Section 5.4, pg 42' },
      { asset: 'PUMP-2547', document: 'Pump Series X OEM Manual', section: '6.2 Seals',       recommendation: 'Inspect seals every 6 months',  frequency: 'Every 6 months', docDate: '2024', evidence: 'Section 6.2, pg 58' },
      { asset: 'COMP-1103', document: 'Compressor OEM Guide',     section: '4.1 Bearings',    recommendation: 'Inspect bearings monthly',      frequency: 'Monthly',        docDate: '2023', evidence: 'Section 4.1, pg 31' },
    ],
    gaps: [
      { asset: 'PUMP-2547', currentPractice: 'Lubricate every 6 months',   oemRecommendation: 'Lubricate every 3 months',         identifiedGap: 'Maintenance interval 2× longer than OEM',     status: 'Gap Identified',  priority: 'High',   evidence: 'OEM Manual 5.4' },
      { asset: 'COMP-1103', currentPractice: 'Inspect bearing quarterly',   oemRecommendation: 'Inspect bearing monthly',          identifiedGap: 'Inspection frequency too low',                 status: 'Review Required', priority: 'High',   evidence: 'OEM Guide 4.1' },
      { asset: 'PUMP-0392', currentPractice: 'Replace seal annually',       oemRecommendation: 'Inspect seal condition every 6 m', identifiedGap: 'Maintenance strategy difference identified',   status: 'Review Required', priority: 'Medium', evidence: 'OEM Manual 6.1' },
      { asset: 'TANK-0051', currentPractice: 'Inspect quarterly',           oemRecommendation: 'Inspect monthly',                  identifiedGap: 'Inspection frequency below OEM guidance',      status: 'Review Required', priority: 'Medium', evidence: 'OEM Tank Guide' },
    ],
    evidence: [
      { asset: 'PUMP-2547', maximo: 'JP-PUMP-2547 — 6-month lubrication',          oem: 'OEM Section 5.4 — 3-month interval',    analysis: 'Gap: interval is 2× longer than OEM guidance',             recommendation: 'Update lubrication task frequency in JP-PUMP-2547' },
      { asset: 'COMP-1103', maximo: 'JP-COMP-1103 — quarterly bearing inspection',  oem: 'OEM Section 4.1 — monthly inspection',  analysis: 'Gap: quarterly vs monthly — potential failure risk',          recommendation: 'Increase bearing inspection to monthly in JP-COMP-1103' },
    ],
  },

  // ── 3. Report ──────────────────────────────────────────────────────────────
  {
    id: 'demo-3',
    actionNumber: 'RP-003',
    demoOnly: true,
    title: 'Maintenance Gap Report — Rotating Equipment Q2 2025',
    description: 'Detailed engineering report covering identified maintenance gaps with supporting OEM evidence and quantified reliability impact.',
    type: 'Report',
    status: 'Completed',
    priority: 'Medium',
    assets: 7,
    created: 'Today, 11:30 AM',
    source: 'Chat',
    sourceConversationId: 'demo-conv-001',
    parentActionId: 'demo-2',
    relatedActions: ['demo-1', 'demo-2', 'demo-7'],
    summary: {
      assetsEvaluated: 15,
      assetsWithGaps: 7,
      assetsRequireReview: 4,
      alignedAssets: 8,
      totalGaps: 10,
      highSeverityGaps: 4,
      mediumSeverityGaps: 3,
      lowSeverityGaps: 3,
    },
    topGapCategories: [
      { category: 'Maintenance Interval',  count: 4 },
      { category: 'Inspection Frequency',  count: 3 },
      { category: 'Maintenance Tasks',     count: 2 },
      { category: 'Lubrication',           count: 1 },
    ],
    potentialImpact: {
      estimatedDowntimeReduction: '620 hrs',
      estimatedCostAvoidance: '$190K',
      reliabilityImprovement: 'High',
    },
    highSeverityGaps: [
      { asset: 'PUMP-2547', category: 'Maintenance Interval',  currentPractice: 'Lubricate every 6 months',      oemRecommendation: 'Lubricate every 3 months',           potentialImpact: 'Bearing wear risk',    priority: 'High' },
      { asset: 'COMP-1103', category: 'Inspection Frequency',  currentPractice: 'Inspect bearing every 3 months', oemRecommendation: 'Inspect monthly',                    potentialImpact: 'Undetected failures',  priority: 'High' },
      { asset: 'PUMP-0392', category: 'Maintenance Tasks',     currentPractice: 'No seal condition check',        oemRecommendation: 'Check seal condition monthly',       potentialImpact: 'Seal failure risk',    priority: 'High' },
      { asset: 'TANK-0051', category: 'Inspection Frequency',  currentPractice: 'Inspect quarterly',              oemRecommendation: 'Inspect monthly',                    potentialImpact: 'Leak detection risk',  priority: 'High' },
    ],
    assetGaps: [
      { asset: 'PUMP-2547', description: 'Booster Pump 2547',  gapCategory: 'Maintenance Interval',  gap: 'Lubrication every 6m vs 3m OEM',   severity: 'High',   status: 'Gap Identified' },
      { asset: 'COMP-1103', description: 'Compressor 1103',    gapCategory: 'Inspection Frequency',  gap: 'Quarterly vs monthly OEM',         severity: 'High',   status: 'Review Required' },
      { asset: 'PUMP-0392', description: 'Process Pump 0392',  gapCategory: 'Maintenance Tasks',     gap: 'No seal condition check in PM',    severity: 'High',   status: 'Review Required' },
      { asset: 'TANK-0051', description: 'Storage Tank 0051',  gapCategory: 'Inspection Frequency',  gap: 'Quarterly vs monthly OEM',         severity: 'Medium', status: 'Review Required' },
    ],
    maintenanceGaps: [
      { category: 'Maintenance Interval', count: 4, severity: 'High',   assets: ['PUMP-2547', 'PUMP-0392', 'TANK-0051', 'MOT-8821'] },
      { category: 'Inspection Frequency', count: 3, severity: 'High',   assets: ['COMP-1103', 'TANK-0051', 'MOT-8821'] },
      { category: 'Maintenance Tasks',    count: 2, severity: 'Medium', assets: ['PUMP-0392', 'COMP-1103'] },
      { category: 'Lubrication',          count: 1, severity: 'Medium', assets: ['PUMP-2547'] },
    ],
    recommendedActions: [
      { action: 'Review job plan JP-PUMP-2547',                     asset: 'PUMP-2547', priority: 'High',   relatedActionId: 'demo-4' },
      { action: 'Increase bearing inspection for COMP-1103',        asset: 'COMP-1103', priority: 'High',   relatedActionId: 'demo-4' },
      { action: 'Add seal condition inspection for PUMP-0392',      asset: 'PUMP-0392', priority: 'High',   relatedActionId: 'demo-4' },
      { action: 'Update inspection schedule for TANK-0051',         asset: 'TANK-0051', priority: 'Medium', relatedActionId: 'demo-4' },
    ],
  },

  // ── 4. Task ────────────────────────────────────────────────────────────────
  {
    id: 'demo-4',
    actionNumber: 'TSK-003',
    demoOnly: true,
    title: 'Job Plan Review Tasks — PUMP-2547 & COMP-1103',
    description: 'Reliability engineering review tasks generated from confirmed maintenance gaps identified in Q2 2025 analysis.',
    type: 'Task',
    status: 'Open',
    priority: 'High',
    assets: 4,
    created: 'Today, 12:01 PM',
    source: 'Chat',
    sourceConversationId: 'demo-conv-001',
    parentActionId: 'demo-3',
    relatedActions: ['demo-1', 'demo-2', 'demo-3'],
    metrics: { openTasks: 4, inProgress: 1, completed: 0, highPriority: 3 },
    tasks: [
      { task: 'Review lubrication interval in JP-PUMP-2547',   asset: 'PUMP-2547', priority: 'High',   owner: 'R. Mehta',  status: 'Open',        created: 'Today, 12:01 PM', dueDate: 'May 25, 2025' },
      { task: 'Increase bearing inspection for COMP-1103',     asset: 'COMP-1103', priority: 'High',   owner: 'A. Kumar',  status: 'Open',        created: 'Today, 12:01 PM', dueDate: 'May 25, 2025' },
      { task: 'Add seal condition check to JP-PUMP-0392',      asset: 'PUMP-0392', priority: 'High',   owner: 'S. Patel',  status: 'Open',        created: 'Today, 12:01 PM', dueDate: 'May 25, 2025' },
      { task: 'Update job plan for TANK-0051',                 asset: 'TANK-0051', priority: 'Medium', owner: 'R. Singh',  status: 'In Progress', created: 'Today, 12:01 PM', dueDate: 'May 28, 2025' },
    ],
    activity: [
      { text: 'Task created: Review lubrication interval in JP-PUMP-2547',       time: 'Today, 12:01 PM' },
      { text: 'Task created: Increase bearing inspection for COMP-1103',          time: 'Today, 12:01 PM' },
      { text: 'Task created: Add seal condition check to JP-PUMP-0392',           time: 'Today, 12:01 PM' },
      { text: 'Task status changed to In Progress: Update job plan for TANK-0051', time: 'Today, 12:07 PM' },
    ],
  },

  // ── 5. Recommendation ──────────────────────────────────────────────────────
  {
    id: 'demo-7',
    actionNumber: 'REC-003',
    demoOnly: true,
    title: 'Reliability Recommendations — Rotating Equipment Program',
    description: 'AI-generated prioritised recommendations to close identified maintenance gaps and improve asset reliability for the rotating equipment fleet.',
    type: 'Recommendation',
    status: 'Proposed',
    priority: 'High',
    assets: 7,
    created: 'Today, 12:30 PM',
    source: 'System',
    sourceConversationId: 'demo-conv-001',
    parentActionId: 'demo-3',
    relatedActions: ['demo-1', 'demo-2', 'demo-3'],
    metrics: { totalRecommendations: 6, highPriority: 4, mediumPriority: 2, reliabilityImpact: 'High' },
    recommendations: [
      { recommendation: 'Align lubrication interval with OEM recommendation for PUMP-2547',  assets: 2, priority: 'High',   expectedBenefit: 'Reduce failures by 30%',          effort: 'Medium', status: 'Proposed' },
      { recommendation: 'Increase bearing inspection frequency for COMP-1103 to monthly',    assets: 2, priority: 'High',   expectedBenefit: 'Prevent recurring failures',       effort: 'Low',    status: 'Proposed' },
      { recommendation: 'Add seal condition check to PM tasks for PUMP-0392',                assets: 1, priority: 'High',   expectedBenefit: 'Early detection of seal wear',     effort: 'Low',    status: 'Proposed' },
      { recommendation: 'Update inspection schedule for TANK-0051 to monthly',               assets: 1, priority: 'High',   expectedBenefit: 'Reduce leak risk',                 effort: 'Low',    status: 'Proposed' },
      { recommendation: 'Standardize all PM tasks against OEM best practices',               assets: 3, priority: 'Medium', expectedBenefit: 'Consistency and traceability',     effort: 'Medium', status: 'Proposed' },
      { recommendation: 'Review and optimize PM schedule frequencies across fleet',           assets: 3, priority: 'Medium', expectedBenefit: 'Better maintenance alignment',     effort: 'Medium', status: 'Proposed' },
    ],
    implementationPlan: [
      { step: 1, action: 'Reliability engineer reviews each recommendation against OEM evidence' },
      { step: 2, action: 'Validate supporting OEM documentation and work order history' },
      { step: 3, action: 'Review affected Maximo job plans (JP-PUMP-2547, JP-COMP-1103, JP-PUMP-0392)' },
      { step: 4, action: 'Obtain engineering and maintenance supervisor approval' },
      { step: 5, action: 'Modify job plans through the established change-control process' },
      { step: 6, action: 'Validate changes in Maximo and confirm PM schedule alignment' },
      { step: 7, action: 'Mark recommendations as Implemented and close associated tasks' },
    ],
    impactAreas: [
      { dimension: 'Affected assets',     value: '7 assets across Units 1–4' },
      { dimension: 'Failure modes',       value: 'Seal failure, bearing wear, lubrication issues' },
      { dimension: 'Downtime exposure',   value: '620 hrs estimated reduction' },
      { dimension: 'Criticality',         value: '4 Critical, 3 High assets addressed' },
      { dimension: 'Reliability benefit', value: 'High — addresses top recurring failure modes' },
    ],
  },
];
