namespace   = "retail-automation"
ocp_server  = "https://c109-e.us-east.containers.cloud.ibm.com:32533"
ocp_token   = "sha256~MxZb2J1NOk7XJ2H2fgBPDbZd6IIHffQG-z6BQ8AU38U"
postgres_db        = "retaildb"
postgres_user      = "retail_user"
postgres_password  = "retail_password"
