version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "6001:6001"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 6001 --reload

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm start