tabtitle = Real-Time AI Guardrails
navbartitle = Real-Time AI Guardrails

layout = horizontal

helper_text = Select a sample scenario and guardrails to begin evaluation. Results will be displayed here.

footer_text = Built with Dash and IBM watsonx.governance | Do not input personal data, or data that is sensitive or confidential into this app. &#169; Copyright IBM Corporation
