coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
query.max-memory=128MB
query.max-memory-per-node=64MB
memory.heap-headroom-per-node=48MB
