apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Patch the ConfigMap to add DB_HOST (private VPE hostname) for prod
patches:
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: add
        path: /data/DB_HOST
        value: "REPLACE_WITH_DB_HOST_PRIVATE"
