apiVersion: v1
kind: Secret
metadata:
  name: rag-credentials
  namespace: tbb
type: Opaque
stringData:
  # IBM Watsonx Credentials
  watsonx-api-key: ${WATSONX_API_KEY}
  watsonx-project-id: ${WATSONX_PROJECT_ID}
  
  # Milvus Credentials
  milvus-password: ${MILVUS_PASSWORD}
