apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: headlessbob
  labels: { app: headlessbob }
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: headlessbob
  labels: { app: headlessbob }
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to: { kind: ImageStreamTag, name: 'headlessbob:latest' }
  resources:
    requests: { cpu: 500m, memory: 1Gi }
    limits: { cpu: '2', memory: 3Gi }
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
