"""
B5 — Motivation Nudge App (thin, implementation-agnostic)
==========================================================
Produces a seller-facing motivation/nudge from unified signals pulled
from the lakehouse (Cassandra live + Iceberg history + Databricks federated).

"Motivation Graph" is a conceptual/brand name only.
No graph database, no networkx, no graph structure. (Spec §A7, §B5, §10, §12.)

Design requirement (§B5):
  The nudge must visibly depend on ≥3 unified sources so the data-integration
  value is legible on screen:
    source_1: Salesforce CDC  (live deal pipeline — Cassandra/Iceberg via B2)
    source_2: Slack Events    (live recognition — Cassandra/Iceberg via B2)
    source_3: Databricks Delta (historical seller metric — query-in-place via B4)

Acceptance (§B5): renders a nudge for one seller derived from ≥3 unified sources.
No graph library required.

Act 3 — AI layer (wx.ai):
  headline and body are generated by IBM watsonx.ai (Granite).
  When the LLM is reachable, _apply_rules() sets framing/fallback text and
  _enrich_with_watsonx_ai() replaces headline + body with LLM output.
  The response is annotated with ai_generated=True and ai_ metadata fields
  so the UI can display an explicit "wx.ai" attribution badge.
  On any LLM failure the SQL-rule strings are preserved (graceful fallback).
"""

from __future__ import annotations

import json
import logging
import re
import uuid
from datetime import datetime
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))
from config import PROGRAM_START

log = logging.getLogger(__name__)

MODEL_VERSION = "sql-rules-v2.0"
NOW_TS = datetime.fromisoformat(PROGRAM_START)

# ── Prompt template ───────────────────────────────────────────────────────────

_NUDGE_PROMPT = """\
You are a motivational coach for enterprise sales teams. Write a short, energizing nudge for a seller.

Seller: {name}
Persona: {persona}
Closed deals (live, Salesforce CDC): {sf_deals}
CRM updates logged (live, Salesforce CDC): {sf_updates}
Peer recognitions received (Slack Events): {recognitions}
Deals closed in last 90 days (Databricks historical): {db_velocity}
Nudge theme: {framing}

Rules:
- headline: one punchy sentence, ≤12 words, personalised with the seller name. No quotation marks.
- body: two to three sentences. Reference the actual numbers above. End with a forward-looking call to action. No quotation marks.
- Output ONLY a single JSON object. No explanation, no markdown, no code fences, no extra text before or after.
- Use exactly these two keys: "headline" and "body".

JSON output:
{{"headline": "...", "body": "..."}}"""


# ── Signal extraction ─────────────────────────────────────────────────────────

def _extract_signals_from_session(con, seller_id: str) -> dict:
    """
    Pull the three required unified-source signals via SQL.
    Works against any DB-API 2.0 connection (Trino / watsonx.data Presto or
    local DuckDB for test/dev).
    """
    def q(sql, params=None):
        cur = con.cursor() if hasattr(con, "cursor") else con
        if params:
            cur.execute(sql, params)
        else:
            cur.execute(sql)
        return cur.fetchone()

    def qn(sql, params=None):
        row = q(sql, params)
        return row[0] if row else 0

    # Source 1: Salesforce CDC — CRM compliance and closed deals
    sf_deals = qn(
        "SELECT COUNT(*) FROM activity_events WHERE seller_id=? AND event_type='deal_closed'",
        [seller_id],
    )
    sf_updates = qn(
        "SELECT COUNT(*) FROM activity_events WHERE seller_id=? AND event_type='crm_update'",
        [seller_id],
    )

    # Source 2: Slack Events — peer recognitions (real-time collaboration signal)
    slack_recognitions = qn(
        "SELECT COUNT(*) FROM activity_events "
        "WHERE seller_id=? AND event_type IN ('peer_recognition', 'mentorship_session')",
        [seller_id],
    )

    # Source 3: Databricks historical metric — deal velocity in last 90 days
    # When B4 is real, Trino federates this to Databricks Delta in place.
    # When running against local DuckDB (test/dev), the synthetic data serves
    # as the representative historical signal.
    deal_velocity_90d = qn(
        "SELECT COUNT(*) FROM activity_events "
        "WHERE seller_id=? AND event_type='deal_closed' "
        "AND event_ts >= (now() - INTERVAL '90 days')",
        [seller_id],
    )

    # Seller display name
    name_row = q(
        "SELECT display_name, tenure_team_months, persona_label FROM sellers WHERE seller_id=?",
        [seller_id],
    )
    display_name  = name_row[0] if name_row else seller_id
    tenure_months = name_row[1] if name_row else 0
    persona_label = name_row[2] if name_row else ""

    return {
        "seller_id":         seller_id,
        "display_name":      display_name,
        "persona_label":     persona_label,
        "tenure_months":     tenure_months,
        # Source 1 — Salesforce CDC
        "sf_deals_closed":   sf_deals,
        "sf_crm_updates":    sf_updates,
        "_source_1":         "Salesforce CDC (live → Cassandra/Iceberg via B2)",
        # Source 2 — Slack Events
        "slack_recognitions": slack_recognitions,
        "_source_2":          "Slack Events (real-time → Cassandra/Iceberg via B2)",
        # Source 3 — Databricks historical metric (federated in place via B4)
        "db_deal_velocity_90d": deal_velocity_90d,
        "_source_3":            "Databricks Delta (historical — query-in-place via B4)",
    }


def _extract_signals_from_watsonx(con, seller_id: str) -> dict:
    """
    Same extraction via WatsonxDataSession (has .execute() + .fetchone() directly).
    """
    def qn(sql, params=None):
        row = con.execute(sql, params or []).fetchone()
        return row[0] if row else 0

    sf_deals = qn(
        "SELECT COUNT(*) FROM activity_events WHERE seller_id=? AND event_type='deal_closed'",
        [seller_id],
    )
    sf_updates = qn(
        "SELECT COUNT(*) FROM activity_events WHERE seller_id=? AND event_type='crm_update'",
        [seller_id],
    )
    slack_recognitions = qn(
        "SELECT COUNT(*) FROM activity_events "
        "WHERE seller_id=? AND event_type IN ('peer_recognition', 'mentorship_session')",
        [seller_id],
    )
    deal_velocity_90d = qn(
        "SELECT COUNT(*) FROM activity_events "
        "WHERE seller_id=? AND event_type='deal_closed' "
        "AND event_ts >= (now() - INTERVAL '90 days')",
        [seller_id],
    )
    name_row = con.execute(
        "SELECT display_name, tenure_team_months, persona_label FROM sellers WHERE seller_id=?",
        [seller_id],
    ).fetchone()
    display_name  = name_row[0] if name_row else seller_id
    tenure_months = name_row[1] if name_row else 0
    persona_label = name_row[2] if name_row else ""

    return {
        "seller_id":            seller_id,
        "display_name":         display_name,
        "persona_label":        persona_label,
        "tenure_months":        tenure_months,
        "sf_deals_closed":      sf_deals,
        "sf_crm_updates":       sf_updates,
        "_source_1":            "Salesforce CDC (live → Cassandra/Iceberg via B2)",
        "slack_recognitions":   slack_recognitions,
        "_source_2":            "Slack Events (real-time → Cassandra/Iceberg via B2)",
        "db_deal_velocity_90d": deal_velocity_90d,
        "_source_3":            "Databricks Delta (historical — query-in-place via B4)",
    }


# ── SQL rules → nudge ─────────────────────────────────────────────────────────

def _apply_rules(signals: dict) -> dict:
    """
    Pure SQL-rules pass: determines framing + fallback headline/body.
    Priority (checked in order):
      1. Active deal + recognition → momentum
      2. High CRM compliance + low deals → pipeline
      3. High recognition count → peer-impact
      4. Default → milestone
    """
    sf_deals     = signals["sf_deals_closed"]
    sf_updates   = signals["sf_crm_updates"]
    recognitions = signals["slack_recognitions"]
    db_velocity  = signals["db_deal_velocity_90d"]
    name         = signals["display_name"]

    if sf_deals >= 1 and recognitions >= 3:
        framing  = "momentum"
        headline = f"{name}, you're building real impact"
        body = (
            f"Your {sf_deals} closed deal(s) and {recognitions} peer recognitions "
            f"(Slack + Salesforce) show you're at full momentum. "
            f"Historical data shows {db_velocity} deals closed in the last 90 days — "
            f"keep that pace into the final stretch."
        )
    elif sf_updates >= 10 and sf_deals == 0:
        framing  = "pipeline"
        headline = f"CRM consistency will turn into closed deals, {name}"
        body = (
            f"You've logged {sf_updates} CRM updates (Salesforce live feed) — "
            f"that discipline is visible across the platform. "
            f"Your Databricks history shows strong pipeline discipline. "
            f"The next deal is close."
        )
    elif recognitions >= 5:
        framing  = "peer-impact"
        headline = f"Your team sees you, {name}"
        body = (
            f"You've earned {recognitions} peer recognitions via Slack — "
            f"the most in your cohort this cycle. "
            f"Databricks history confirms your deal pace ({db_velocity} in 90 days). "
            f"One more close unlocks the next milestone."
        )
    else:
        framing  = "milestone"
        headline = f"Your next milestone is within reach, {name}"
        body = (
            f"Salesforce shows {sf_deals} deals closed and {sf_updates} CRM updates. "
            f"Slack recognition: {recognitions} this cycle. "
            f"Databricks historical pace: {db_velocity} deals in 90 days. "
            f"Everything is pointing up — finish strong."
        )

    return {
        "nudge_id":    "nudge-" + str(uuid.uuid4())[:8],
        "seller_id":   signals["seller_id"],
        "display_name": signals["display_name"],
        "persona_label": signals.get("persona_label", ""),
        "framing":     framing,
        "headline":    headline,
        "body":        body,
        "unified_sources": [
            signals["_source_1"],
            signals["_source_2"],
            signals["_source_3"],
        ],
        "source_signals": {
            "salesforce_deals_closed":       signals["sf_deals_closed"],
            "salesforce_crm_updates":        signals["sf_crm_updates"],
            "slack_recognitions":            signals["slack_recognitions"],
            "databricks_deal_velocity_90d":  signals["db_deal_velocity_90d"],
        },
        "model_version": MODEL_VERSION,
        "generated_at":  datetime.utcnow().isoformat(timespec="seconds") + "Z",
        # Act 3 AI fields — populated by _enrich_with_watsonx_ai(); defaults = rule-based
        "ai_generated":  False,
        "ai_model_id":   None,
        "ai_request_id": None,
        # Compliance labels (§B5, Hardening Addendum §0)
        "_simulated_data": True,
        "_real_engines":   True,
    }


# ── Act 3 — watsonx.ai enrichment ────────────────────────────────────────────

def _enrich_with_watsonx_ai(nudge: dict, signals: dict) -> dict:
    """
    Replace the SQL-rule headline + body with LLM-generated text from
    IBM watsonx.ai (Granite).  On any failure the original strings are
    kept unchanged (graceful fallback).

    Returns the (possibly mutated) nudge dict.
    """
    try:
        import sys
        from pathlib import Path as _Path
        sys.path.insert(0, str(_Path(__file__).parent.parent))
        from ibm_services import IBMServiceManager

        mgr = IBMServiceManager()
        # Probe only watsonx.ai (skip the full gate which requires all services)
        mgr.reachability_results = [mgr._probe_watsonx_ai()]

        prompt = _NUDGE_PROMPT.format(
            name=signals["display_name"],
            persona=signals.get("persona_label", "seller"),
            sf_deals=signals["sf_deals_closed"],
            sf_updates=signals["sf_crm_updates"],
            recognitions=signals["slack_recognitions"],
            db_velocity=signals["db_deal_velocity_90d"],
            framing=nudge["framing"],
        )

        ai_result = mgr.generate_with_watsonx_ai(prompt)

        # Parse the JSON payload the model returns.
        # Use regex to pull the first {...} block — works even when the model
        # wraps the JSON in prose or markdown code fences.
        raw = ai_result.text.strip()
        m = re.search(r'\{[^{}]*"headline"[^{}]*"body"[^{}]*\}|'
                      r'\{[^{}]*"body"[^{}]*"headline"[^{}]*\}', raw, re.DOTALL)
        if not m:
            log.warning("wx.ai text did not contain a JSON object with headline+body — falling back")
            log.debug("wx.ai raw text: %s", raw[:500])
            return nudge
        parsed = json.loads(m.group())

        headline = str(parsed.get("headline", "")).strip()
        body     = str(parsed.get("body", "")).strip()

        if headline and body:
            nudge["headline"]    = headline
            nudge["body"]        = body
            nudge["ai_generated"]  = True
            nudge["ai_model_id"]   = ai_result.model_id
            nudge["ai_request_id"] = ai_result.request_id
            log.info(
                "wx.ai nudge generated request_id=%s model=%s",
                ai_result.request_id, ai_result.model_id,
            )
        else:
            log.warning("wx.ai returned empty headline or body — keeping rule-based text")

    except Exception as exc:  # noqa: BLE001
        # Any error (unreachable, bad JSON, etc.) → keep rule-based text silently
        log.info("wx.ai enrichment skipped (%s: %s) — using rule-based fallback", type(exc).__name__, exc)

    return nudge


# ── Public API ────────────────────────────────────────────────────────────────

def generate_motivation_nudge(con, seller_id: str) -> dict:
    """
    Entry point for WatsonxDataSession (has .execute() returning cursor-like objects).
    No graph, no networkx. (§B5, §A7, §10)
    Calls watsonx.ai to replace headline + body with LLM text (Act 3).
    """
    signals = _extract_signals_from_watsonx(con, seller_id)
    nudge   = _apply_rules(signals)
    return _enrich_with_watsonx_ai(nudge, signals)


def generate_motivation_nudge_duckdb(con, seller_id: str) -> dict:
    """
    Entry point for local DuckDB connection (has DB-API 2.0 cursor).
    Used by the API server and tests when watsonx.data is not reachable.
    Calls watsonx.ai to replace headline + body with LLM text (Act 3).
    """
    signals = _extract_signals_from_session(con, seller_id)
    nudge   = _apply_rules(signals)
    return _enrich_with_watsonx_ai(nudge, signals)


def generate_all_nudges(con) -> list[dict]:
    """
    Generate nudges for all three foreground sellers.
    Accepts WatsonxDataSession or DuckDB connection.
    """
    sellers = ["seller-rachel-001", "seller-marcus-001", "seller-maya-001"]
    fn = (generate_motivation_nudge
          if hasattr(con, "execute") and not hasattr(con, "cursor")
          else generate_motivation_nudge_duckdb)
    return [fn(con, sid) for sid in sellers]
